[build]
builder = "nixpacks"

[variables]
PORT = "5000"

[phases.setup]
nixPkgs = ["python311", "bash"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python -m playwright install"
]

[start]
cmd = "python app.py"